name: Web Monitoring

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  monitor:
    runs-on: windows-latest  # Run on Windows runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Setup Python environment
        with:
          python-version: '3.x'  # Specify Python version

      - name: Install requests library
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install requests  # Install the requests library

      - name: Run web monitor
        run: python web_monitor.py  # Run the web monitor script
