name: Web Monitoring

on:
  push:  # Trigger workflow on push

jobs:
  monitor:
    runs-on: windows-latest  # Run on Windows runner
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}  # Pass the Slack token as an environment variable from GitHub Secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Setup Python environment
        with:
          python-version: '3.x'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install requests selenium webdriver-manager slack-sdk  # Install dependencies

      - name: Run web monitor
        run: python web_monitor.py  # Run the web monitor script
